# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import msg_pb2 as msg__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in msg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestAccess = channel.unary_unary(
                '/FileControl/TestAccess',
                request_serializer=msg__pb2.TestAccessRequest.SerializeToString,
                response_deserializer=msg__pb2.TestAccessAnswer.FromString,
                _registered_method=True)
        self.AddFile = channel.unary_unary(
                '/FileControl/AddFile',
                request_serializer=msg__pb2.AddFileRequest.SerializeToString,
                response_deserializer=msg__pb2.AddFileAnswer.FromString,
                _registered_method=True)


class FileControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.TestAccess,
                    request_deserializer=msg__pb2.TestAccessRequest.FromString,
                    response_serializer=msg__pb2.TestAccessAnswer.SerializeToString,
            ),
            'AddFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFile,
                    request_deserializer=msg__pb2.AddFileRequest.FromString,
                    response_serializer=msg__pb2.AddFileAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileControl/TestAccess',
            msg__pb2.TestAccessRequest.SerializeToString,
            msg__pb2.TestAccessAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileControl/AddFile',
            msg__pb2.AddFileRequest.SerializeToString,
            msg__pb2.AddFileAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
