# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cServer.proto\"(\n\x11TestAccessRequest\x12\x13\n\x0brequestInfo\x18\x01 \x01(\t\"&\n\x10TestAccessAnswer\x12\x12\n\nanswerInfo\x18\x01 \x01(\t2=\n\x06Server\x12\x33\n\nTestAccess\x12\x12.TestAccessRequest\x1a\x11.TestAccessAnswerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTACCESSREQUEST']._serialized_start=16
  _globals['_TESTACCESSREQUEST']._serialized_end=56
  _globals['_TESTACCESSANSWER']._serialized_start=58
  _globals['_TESTACCESSANSWER']._serialized_end=96
  _globals['_SERVER']._serialized_start=98
  _globals['_SERVER']._serialized_end=159
# @@protoc_insertion_point(module_scope)
