# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_protobuf import DataBase_pb2 as grpc__protobuf_dot_DataBase__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_protobuf/DataBase_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataBaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitDataBase = channel.unary_unary(
                '/DataBase/InitDataBase',
                request_serializer=grpc__protobuf_dot_DataBase__pb2.InitRequest.SerializeToString,
                response_deserializer=grpc__protobuf_dot_DataBase__pb2.InitAnswer.FromString,
                _registered_method=True)


class DataBaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitDataBase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataBaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitDataBase': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDataBase,
                    request_deserializer=grpc__protobuf_dot_DataBase__pb2.InitRequest.FromString,
                    response_serializer=grpc__protobuf_dot_DataBase__pb2.InitAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataBase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DataBase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataBase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitDataBase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataBase/InitDataBase',
            grpc__protobuf_dot_DataBase__pb2.InitRequest.SerializeToString,
            grpc__protobuf_dot_DataBase__pb2.InitAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
