# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_protobuf/DataBase.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc_protobuf/DataBase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgrpc_protobuf/DataBase.proto\"#\n\x0bInitRequest\x12\x14\n\x0c\x44\x61taBasePath\x18\x01 \x01(\t\"_\n\nInitAnswer\x12\"\n\x06result\x18\x01 \x01(\x0e\x32\x12.InitAnswer.Result\x12\x0c\n\x04info\x18\x02 \x01(\t\"\x1f\n\x06Result\x12\x0b\n\x07success\x10\x00\x12\x08\n\x04\x46\x61il\x10\x01\x32\x35\n\x08\x44\x61taBase\x12)\n\x0cInitDataBase\x12\x0c.InitRequest\x1a\x0b.InitAnswerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_protobuf.DataBase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=32
  _globals['_INITREQUEST']._serialized_end=67
  _globals['_INITANSWER']._serialized_start=69
  _globals['_INITANSWER']._serialized_end=164
  _globals['_INITANSWER_RESULT']._serialized_start=133
  _globals['_INITANSWER_RESULT']._serialized_end=164
  _globals['_DATABASE']._serialized_start=166
  _globals['_DATABASE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
