# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Server_pb2 as Server__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestAccess = channel.unary_unary(
                '/Server/TestAccess',
                request_serializer=Server__pb2.TestAccessRequest.SerializeToString,
                response_deserializer=Server__pb2.TestAccessAnswer.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestAccess(self, request, context):
        """rpc GetChecking(idMessage) returns (CheckResult);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.TestAccess,
                    request_deserializer=Server__pb2.TestAccessRequest.FromString,
                    response_serializer=Server__pb2.TestAccessAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/TestAccess',
            Server__pb2.TestAccessRequest.SerializeToString,
            Server__pb2.TestAccessAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
