# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Server.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'Server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cServer.proto\"(\n\x11TestAccessRequest\x12\x13\n\x0brequestInfo\x18\x01 \x01(\t\"&\n\x10TestAccessAnswer\x12\x12\n\nanswerInfo\x18\x01 \x01(\t\"\x1c\n\tidMessage\x12\x0f\n\x07\x63heckId\x18\x01 \x01(\t\"\x84\x01\n\x0b\x43heckResult\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.CheckResult.Result\x12\x0f\n\x07\x63heckId\x18\x02 \x03(\t\x12\x11\n\tcheckInfo\x18\x03 \x03(\t\",\n\x06Result\x12\x0b\n\x07success\x10\x00\x12\x15\n\x11\x63heckId_not_Found\x10\x01\x32\x66\n\x06Server\x12\x33\n\nTestAccess\x12\x12.TestAccessRequest\x1a\x11.TestAccessAnswer\x12\'\n\x0bGetChecking\x12\n.idMessage\x1a\x0c.CheckResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTACCESSREQUEST']._serialized_start=16
  _globals['_TESTACCESSREQUEST']._serialized_end=56
  _globals['_TESTACCESSANSWER']._serialized_start=58
  _globals['_TESTACCESSANSWER']._serialized_end=96
  _globals['_IDMESSAGE']._serialized_start=98
  _globals['_IDMESSAGE']._serialized_end=126
  _globals['_CHECKRESULT']._serialized_start=129
  _globals['_CHECKRESULT']._serialized_end=261
  _globals['_CHECKRESULT_RESULT']._serialized_start=217
  _globals['_CHECKRESULT_RESULT']._serialized_end=261
  _globals['_SERVER']._serialized_start=263
  _globals['_SERVER']._serialized_end=365
# @@protoc_insertion_point(module_scope)
